export let data = [
    {
        name:`Jane Cooper
        Jane Cooper
        Jane Cooper`,
        company:`Microsoft Microsoft Microsoft Microsoft Microsoft`,
        phone:`(225) 555-0118`,
        email:`jane@microsoft.comjane@microsoft.com jane@microsoft.com
        jane@microsoft.com jane@microsoft.com`,
        country:`United States`,
        status: true,
    },
    {
        name:`Floyd Miles`,
        company:`Yahoo`,
        phone:`(205) 555-0100`,
        email:`floyd@yahoo.com`,
        country:`Kiribati`,
        status:false,
    },
    {
        name:`Ronald Richards`,
        company:`Adobe`,
        phone:`(302) 555-0107`,
        email:`ronald@adobe.com`,
        country:`Israel`,
        status:false,
    },
    {
        name:`Marvin McKinney`,
        company:`Tesla`,
        phone:`(252) 555-0126`,
        email:`marvin@tesla.com`,
        country:`Iran`,
        status:true,
    },
    {
        name:`Ostin Mc mayer`,
        company:`Apple`,
        phone:`(344) 444-5674`,
        email:`marvin@apple.com`,
        country:`USA`,
        status:true,
    },
    {
        name:`Steven Brown`,
        company:`Uber`,
        phone:`(334) 335-6059`,
        email:`marvin@uber.com`,
        country:`Poland`,
        status:true,
    },
    {
        name:`Marvin McKinney`,
        company:`SO`,
        phone:`(243) 335-4423`,
        email:`marvin@so.com`,
        country:`Spain`,
        status:false,
    },
    {
        name:`Marvin McKinney`,
        company:`Tesla`,
        phone:`(252) 555-0126`,
        email:`marvin@tesla.com`,
        country:`Iran`,
        status:true,
    },
    {
        name:`Jerome Bell`,
        company:`Google`,
        phone:`(629) 555-0129`,
        email:`jerome@google.com`,
        country:`Réunion`,
        status:true,
    },
    {
        name:`Kathryn Murphy`,
        company:`Microsoft`,
        phone:`(406) 555-0120`,
        email:`kathryn@microsoft.com`,
        country:`Curaçao`,
        status:true,
    },
    {
        name:`Jacob Jones`,
        company:`Yahoo`,
        phone:`(208) 555-0112`,
        email:`jacob@yahoo.com`,
        country:`Brazil`,
        status:true,
    },
    {
        name:`Kristin Watson`,
        company:`Facebook`,
        phone:`(704) 555-0127`,
        email:`kristin@facebook.com`,
        country:`Åland Islands`,
        status:false,
    },


    {
        name:`Jane Cooper`,
        company:`Microsoft`,
        phone:`(225) 555-0118`,
        email:`jane@microsoft.com`,
        country:`United States`,
        status: true,
    },
    {
        name:`Floyd Miles`,
        company:`Yahoo`,
        phone:`(205) 555-0100`,
        email:`floyd@yahoo.com`,
        country:`Kiribati`,
        status:false,
    },
    {
        name:`Ronald Richards`,
        company:`Adobe`,
        phone:`(302) 555-0107`,
        email:`ronald@adobe.com`,
        country:`Israel`,
        status:false,
    },
    {
        name:`Marvin McKinney`,
        company:`Tesla`,
        phone:`(252) 555-0126`,
        email:`marvin@tesla.com`,
        country:`Iran`,
        status:true,
    },
    {
        name:`Jerome Bell`,
        company:`Google`,
        phone:`(629) 555-0129`,
        email:`jerome@google.com`,
        country:`Réunion`,
        status:true,
    },
    {
        name:`Kathryn Murphy`,
        company:`Microsoft`,
        phone:`(406) 555-0120`,
        email:`kathryn@microsoft.com`,
        country:`Curaçao`,
        status:true,
    },
    {
        name:`Jacob Jones`,
        company:`Yahoo`,
        phone:`(208) 555-0112`,
        email:`jacob@yahoo.com`,
        country:`Brazil`,
        status:true,
    },
    {
        name:`Kristin Watson`,
        company:`Facebook`,
        phone:`(704) 555-0127`,
        email:`kristin@facebook.com`,
        country:`Åland Islands`,
        status:false,
    },
    {
        name:`Jane Cooper`,
        company:`Microsoft`,
        phone:`(225) 555-0118`,
        email:`jane@microsoft.com`,
        country:`United States`,
        status: true,
    },
    {
        name:`Floyd Miles`,
        company:`Yahoo`,
        phone:`(205) 555-0100`,
        email:`floyd@yahoo.com`,
        country:`Kiribati`,
        status:false,
    },
    {
        name:`Ronald Richards`,
        company:`Adobe`,
        phone:`(302) 555-0107`,
        email:`ronald@adobe.com`,
        country:`Israel`,
        status:false,
    },
    {
        name:`Marvin McKinney`,
        company:`Tesla`,
        phone:`(252) 555-0126`,
        email:`marvin@tesla.com`,
        country:`Iran`,
        status:true,
    },
    {
        name:`Jerome Bell`,
        company:`Google`,
        phone:`(629) 555-0129`,
        email:`jerome@google.com`,
        country:`Réunion`,
        status:true,
    },
    {
        name:`Kathryn Murphy`,
        company:`Microsoft`,
        phone:`(406) 555-0120`,
        email:`kathryn@microsoft.com`,
        country:`Curaçao`,
        status:true,
    },
    {
        name:`Jacob Jones`,
        company:`Yahoo`,
        phone:`(208) 555-0112`,
        email:`jacob@yahoo.com`,
        country:`Brazil`,
        status:true,
    },
    {
        name:`Kristin Watson`,
        company:`Facebook`,
        phone:`(704) 555-0127`,
        email:`kristin@facebook.com`,
        country:`Åland Islands`,
        status:false,
    },
    {
        name:`Jane Cooper`,
        company:`Microsoft`,
        phone:`(225) 555-0118`,
        email:`jane@microsoft.com`,
        country:`United States`,
        status: true,
    },
    {
        name:`Floyd Miles`,
        company:`Yahoo`,
        phone:`(205) 555-0100`,
        email:`floyd@yahoo.com`,
        country:`Kiribati`,
        status:false,
    },
    {
        name:`Ronald Richards`,
        company:`Adobe`,
        phone:`(302) 555-0107`,
        email:`ronald@adobe.com`,
        country:`Israel`,
        status:false,
    },
    {
        name:`Marvin McKinney`,
        company:`Tesla`,
        phone:`(252) 555-0126`,
        email:`marvin@tesla.com`,
        country:`Iran`,
        status:true,
    },
    {
        name:`Jerome Bell`,
        company:`Google`,
        phone:`(629) 555-0129`,
        email:`jerome@google.com`,
        country:`Réunion`,
        status:true,
    },
    {
        name:`Kathryn Murphy`,
        company:`Microsoft`,
        phone:`(406) 555-0120`,
        email:`kathryn@microsoft.com`,
        country:`Curaçao`,
        status:true,
    },
    {
        name:`Jacob Jones`,
        company:`Yahoo`,
        phone:`(208) 555-0112`,
        email:`jacob@yahoo.com`,
        country:`Brazil`,
        status:true,
    },
    {
        name:`Kristin Watson`,
        company:`Facebook`,
        phone:`(704) 555-0127`,
        email:`kristin@facebook.com`,
        country:`Åland Islands`,
        status:false,
    },
]


// let obj = [
//     {"index": 0,"isActive": true, "balance": "$2,226.60", "name": "Eugenia Sawyer", "gender": "female", "phone": "+1 (840) 583-3207", "address": "949 John Street, Rose, Puerto Rico, 1857" },
//     {"index": 1,"isActive": true,"balance": "$2,613.77","name": "Pauline Gallegos","gender": "female","phone": "+1 (985) 593-3328","address": "328 Greenpoint Avenue, Torboy, North Dakota, 6857"},
//     {"index": 2,"isActive": false,"balance": "$3,976.41","name": "Middleton Chaney","gender": "male","phone": "+1 (995) 591-2478","address": "807 Fleet Walk, Brutus, Arkansas, 9783"},
//     {"index": 3,"isActive": true,"balance": "$1,934.58","name": "Burns Poole","gender": "male","phone": "+1 (885) 559-3422","address": "730 Seba Avenue, Osage, Alabama, 6290"},
//     {"index": 4,"isActive": true,"balance": "$3,261.65","name": "Mcfadden Horne","gender": "male","phone": "+1 (942) 565-3988","address": "120 Scholes Street, Kirk, Michigan, 1018"},
//     { "index": 5,"isActive": false, "balance": "$1,790.56", "name": "Suzette Lewis", "gender": "female", "phone": "+1 (837) 586-3283", "address": "314 Dunne Place, Bawcomville, Guam, 9053" }]
//
// obj.reduce((accum, { balance}) => {
//     if(+balance.toString().replace(/[^.0-9]/g,'') > 2000) {
//         return accum + +balance.toString().replace(/[^.0-9]/g,'')
//     }
//     return Math.round(accum * 100) / 100
// }, 0)